[tool.pdm]

[project]
name = ""
version = ""
description = ""
authors = [
    {name = "Rahul", email = "basicfunc@gmail.com"},
]
dependencies = [
    "pygame>=2.3.0",
]
requires-python = ">=3.10"
license = {text = "MIT"}
